# v1
name: Tetikleyici

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  tetikle:
    runs-on: ubuntu-latest
    steps:
      - name: Haber botunu tetikle
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'haber-botu.yml',
              ref: 'main'
            });
            console.log('Haber botu tetiklendi.');
